name: AIRMX
version: '0.1.3'
slug: airmx-addon
description: Local control AIRMX devices
url: https://github.com/dext0r/airmx
image: shilazi/ha-addon-airmx
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: system
ports:
  25880/tcp: 25880
  25883/tcp: 25883
